# Development override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development Server - install deps and run locally
  server:
    image: node:20-alpine
    working_dir: /app
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ENABLE_SWAGGER: true
      ENABLE_CORS_CREDENTIALS: true
    #  MONGODB_URI: mongodb://f1admin:f1password@mongodb:27017/f1-champions?authSource=admin
      REDIS_URL: redis://redis:6379
      DB_HOST: mongodb://f1admin:f1password@mongodb:27017/f1-champions?authSource=admin
    volumes:
      # Mount entire project for workspace dependencies
      - ./:/workspace:cached
      - ./apps/server:/app:cached
      - server_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongodb
      - redis

  # Development Client - install deps and run locally
  client:
    image: node:20-alpine
    working_dir: /app
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4000
    volumes:
      # Mount entire project for workspace dependencies
      - ./:/workspace:cached
      - ./apps/client:/app:cached
      - ./tsconfig.base.json:/tsconfig.base.json:cached
      - client_node_modules:/app/node_modules
      - client_next:/app/.next
    command: sh -c "npm install && npm run dev"

  # Enable development tools
  mongo-express:
    profiles: []  # Remove from dev profile (always run in dev)
    
  redis-commander:
    profiles: []  # Remove from dev profile (always run in dev)

volumes:
  server_node_modules:
  client_node_modules:
  client_next: