# Development override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development Server with hot reload
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: development  # If you add multi-stage dockerfile
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ENABLE_SWAGGER: true
      ENABLE_CORS_CREDENTIALS: true
    volumes:
      # Mount source code for hot reload
      - ./apps/server:/app
      - /app/node_modules
    command: npm run dev

  # Development Client with hot reload
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      target: development  # If you add multi-stage dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload
      - ./apps/client:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Enable development tools
  adminer:
    profiles: []  # Remove from dev profile (always run in dev)
    
  redis-commander:
    profiles: []  # Remove from dev profile (always run in dev)