[build]
builder = "NIXPACKS"

[deploy]
image = "ghcr.io/mashhhok/f1-champ/server:latest"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "4000"
ALLOWED_ORIGINS = "https://client-production-adf9.up.railway.app,http://localhost:3000" 