[build]
builder = "NIXPACKS"

[deploy]
image = "ghcr.io/mashhhok/f1-champ/client:latest"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://client-production-adf9.up.railway.app"