[build]
builder = "NIXPACKS"

[build.buildCommand]
environment = { NEXT_PUBLIC_API_URL = "https://server-production-adf9.up.railway.app" }

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://server-production-adf9.up.railway.app"