name: Deploy Client to Railway

on:
  push:
    branches: [main]
    paths:
      - 'apps/client/**'
      - 'package*.json'
      - '.github/workflows/deploy-client.yml'
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install client dependencies
        run: |
          cd apps/client
          npm install

      - name: Run tests for client
        run: npx nx test client

      - name: Build client
        run: |
          cd apps/client
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.RAILWAY_CLIENT_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./apps/client 